import { TDokTypInfo, TKontrahentInfo, TOsobaInfo, TWydzialInfo, TZalacznikInfo } from './typy-info.model';
import { DaneFinansowe } from './dane-finansowe.model';

export interface Dokument {
  numer: number;
  archiwum: boolean;
  dokGlowny: number;
  wersja: string;
  aktualny: boolean;
  statusEdycji: string;
  doWgladu: boolean;
  typ: TDokTypInfo;
  szablon: string | null;
  nazwa: string;
  opis: string;
  sprawa: any;
  rejestr: string;
  rejestrNumer: number;
  rejestrRok: number;
  rejestrNrPozycji: string;
  dataWplywu: string;
  godzinaWplywu: number;
  numerNaDok: string;
  dataNaDok: string;
  kanalWe: string;
  domKanalWy: string;
  kontrahent: TKontrahentInfo;
  przekazujacy: TOsobaInfo;
  przekazujacyWydzial: TWydzialInfo;
  dataPrzekazania: string;
  prowadzacy: TOsobaInfo;
  prowadzacyWydzial: TWydzialInfo;
  odpowiedzialny: TOsobaInfo;
  dataPrzyjecia: string;
  uprawPoziom: string;
  statusPrzek: string;
  dataAlert: string;
  dataPlan: string;
  daneFinansowe: DaneFinansowe | null;
  grupa1: string;
  grupa2: string;
  grupa3: string;
  publiczny: boolean;
  dokGuid: string;
  jrwa: string;
  zalaczniki: TZalacznikInfo[];
  oper: string;
  status: string;
  statusDane: string;
}