import { TOsobaInfo, TWydzialInfo, TKontrahentInfo, TDokTypInfo, TSzablonInfo, TZalacznikInfo, TSprawaInfo } from './typy-info.model';
import { DaneFinansowe } from './dane-finansowe.model';
import { TBazaOper, TeSodStatus, TStatusEdycji, TKanalTyp } from './enums.model';

export interface Dokument {
  numer: number;
  archiwum: boolean;
  dokGlowny: number;
  wersja: number;
  aktualny: boolean;
  statusEdycji?: TStatusEdycji;
  doWgladu: boolean;
  typ: TDokTypInfo;
  szablon: TSzablonInfo | null;
  nazwa: string;
  opis?: string;
  sprawa: TSprawaInfo | null;
  rejestr: string;
  rejestrNumer: number;
  rejestrRok: number;
  rejestrNrPozycji: string;
  dataWplywu: string;
  godzinaWplywu: number;
  numerNaDok?: string;
  dataNaDok?: string;
  kanalWe?: TKanalTyp;
  domKanalWy?: TKanalTyp;
  kontrahent: TKontrahentInfo;
  przekazujacy: TOsobaInfo;
  przekazujacyWydzial: TWydzialInfo;
  dataPrzekazania: string;
  prowadzacy: TOsobaInfo;
  prowadzacyWydzial: TWydzialInfo;
  odpowiedzialny: TOsobaInfo | null;
  dataPrzyjecia?: string;
  uprawPoziom: string;
  statusPrzek: string;
  dataAlert?: string;
  dataPlan?: string;
  daneFinansowe: DaneFinansowe | null;
  grupa1?: string;
  grupa2?: string;
  grupa3?: string;
  publiczny: boolean;
  dokGuid?: string;
  jrwa?: string;
  obcyNumer?: string;
  zalaczniki: TZalacznikInfo[];
  oper: TBazaOper;
  status: TeSodStatus;
  statusDane: string;
}